# Generated by Django 3.0.4 on 2020-05-01 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=20, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=20, verbose_name='Отчество')),
                ('phones', models.TextField(blank=True, verbose_name='Телефоны')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='E-mail')),
                ('skype', models.CharField(blank=True, max_length=50, verbose_name='Skype')),
                ('vk', models.URLField(blank=True, max_length=50, verbose_name='vk.com')),
                ('status', models.CharField(choices=[('STUDENT', 'Ученик'), ('PARENT', 'Родитель'), ('OTHER', 'Другое')], default='STUDENT', max_length=10, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Human', verbose_name='Ребенок')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, verbose_name='Тема')),
                ('description', models.TextField(verbose_name='Описание')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата/Время')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Course', verbose_name='Курс')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Human', verbose_name='Ученик')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Theme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'managed': True,
            },
        ),
    ]
