# Generated by Django 3.0.4 on 2020-05-01 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Course', verbose_name='Курс')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Human', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Распределение',
                'verbose_name_plural': 'Распределения',
                'managed': True,
            },
        ),
    ]
