# Generated by Django 3.0.4 on 2020-05-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20200501_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='decription',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
