# Generated by Django 3.0.4 on 2020-05-01 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_lesson_decription'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Статус')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Theme', verbose_name='Пункт плана')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Human', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Пункт плана',
                'verbose_name_plural': 'Пункты планов',
                'managed': True,
            },
        ),
    ]
