# Generated by Django 3.0.4 on 2020-05-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_studentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='discord',
            field=models.CharField(blank=True, max_length=50, verbose_name='Discord'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='theme',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тема'),
        ),
    ]
