# Generated by Django 3.0.4 on 2020-05-03 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20200502_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Оплата'),
            preserve_default=False,
        ),
    ]
