# Generated by Django 3.0.4 on 2020-05-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_lesson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='bill',
            field=models.BooleanField(default=False, verbose_name='Счет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер занятия'),
        ),
    ]
