# Generated by Django 3.0.4 on 2020-05-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20200503_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Тип контакта')),
            ],
            options={
                'verbose_name': 'Тип контакта',
                'verbose_name_plural': 'Типы контактов',
                'managed': True,
            },
        ),
        migrations.RenameModel(
            old_name='Destribution',
            new_name='Distribution',
        ),
        migrations.RemoveField(
            model_name='human',
            name='discord',
        ),
        migrations.RemoveField(
            model_name='human',
            name='email',
        ),
        migrations.RemoveField(
            model_name='human',
            name='phones',
        ),
        migrations.RemoveField(
            model_name='human',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='human',
            name='vk',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='number',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='status',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='theme',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тема'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.TextField(blank=True, verbose_name='Контакт')),
                ('human', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Human', verbose_name='Человек')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.ContactType', verbose_name='Тип контакта')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Оплата')),
                ('billingDate', models.DateTimeField(verbose_name='Дата выставления')),
                ('receiptDate', models.DateTimeField(verbose_name='Дата получения')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Human', verbose_name='Кому')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Lesson', verbose_name='За что')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'managed': True,
            },
        ),
    ]
