# Generated by Django 3.0.4 on 2020-05-03 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_lesson_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='ammount',
            field=models.FloatField(default=0, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='bill',
            name='text',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Lesson', verbose_name='Занятие'),
        ),
    ]
