# Generated by Django 3.0.4 on 2020-05-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20200504_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='lesson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Lesson', verbose_name='Занятие'),
        ),
    ]
