# Generated by Django 3.0.4 on 2020-05-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20200506_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='number',
            field=models.IntegerField(default=0, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='human',
            name='status',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Ученик'), ('PARENT', 'Родитель'), ('OTHER', 'Другое')], default='STUDENT', max_length=10, verbose_name='Тип'),
        ),
    ]
