# Generated by Django 3.0.4 on 2020-05-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20200511_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentitem',
            name='number',
            field=models.IntegerField(default=0, null=True, verbose_name='Номер'),
        ),
    ]
